# Generated by Django 5.0.4 on 2024-04-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='expiry',
            field=models.DateField(),
        ),
    ]
